odyssey:
  image: "registry.sirius.online/infra/odyssey"
  imageTag: "v1.3"
  imagePullPolicy: IfNotPresent

pgbouncer:
  image: "registry.sirius.online/infra/pgbouncer-exporter"
  imageTag: "v0.7.0"
  imagePullPolicy: IfNotPresent

postgres:
  image: "registry.sirius.online/cheops-edu/cheops-infra/postgres"
  imageTag: "11.5"
  imagePullPolicy: IfNotPresent
  host: ""
  port: 5432
  username: ""
  database: ""

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

imagePullSecrets: []

nodeSelector: {}

affinity: {}

tolerations: []

annotations: {}

serviceMonitor:
  enabled: true