apiVersion: v1
data:
  odyssey.conf: |
    ### Local development inside Docker
    ###
    ### For configuration information see:
    ### https://github.com/yandex/odyssey/blob/master/documentation/configuration.md
kind: ConfigMap
metadata:
  labels:
    app: {{ template "odyssey.fullname" . }}
    release: {{ .Release.Name }}
  name: {{ template "odyssey.fullname" . }}
  namespace: {{ .Release.Namespace }}