apiVersion: v1
data:
  odyssey.conf: {{ .Values.odyssey.config | required "odyssey.config is required" | toYaml | nindent 4 }}
kind: ConfigMap
metadata:
  labels:
    app: {{ template "odyssey.fullname" . }}
    release: {{ .Release.Name }}
  name: {{ template "odyssey.fullname" . }}
  namespace: {{ .Release.Namespace }}