apiVersion: v1
data:
  odyssey.conf: |
    ### Local development inside Docker
    ###
    ### For configuration information see:
    ### https://github.com/yandex/odyssey/blob/master/documentation/configuration.md
    storage "postgres_server" {
      type "remote
      host "univ-postgres.postgres-prod.svc
      port 5432
      tls  "disable
    }

    database default {
      user default {
        storage "postgres_server
        authentication "clear_text
        storage_user "cheops_prod
        storage_password "huL07sxaPiOBGb15pbxbrqd7YrBnSawG5kOVWpaQObXsxd276jUm5rZ3q38yS82v
        password "huL07sxaPiOBGb15pbxbrqd7YrBnSawG5kOVWpaQObXsxd276jUm5rZ3q38yS82v
        pool "session
        client_max 5000
        pool_size 400
        pool_cancel yes
        pool_rollback yes
        client_fwd_error yes
       }
    }
    storage "local" {
      type "local
    }
    database "console" {
      user default {
         authentication "none
         pool "session
         storage "local
       }
    }

    unix_socket_dir "/tmp
    unix_socket_mode "0644
    log_format "[%t] %l %c %d %h:%r %m\n

    #log_format {\"severity\":\"%l\",\"time\":\"%t\",\"message\":\"%m\",\"context\":\"%c\",\"thread\":\"%p\", \"client\":\"%h:%r\", \"database\":\"%d\", \"username\":\"%u\"}

    log_debug no
    log_config no
    log_session no
    log_query no
    log_stats no
    stats_interval 60
    workers 1
    listen {
       host "*
       port 6432
    }
kind: ConfigMap
metadata:
  labels:
    app: odyssey
  name: odyssey
