apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: {{ template "odyssey.fullname" . }}
  labels:
    app: {{ template "odyssey.fullname" . }}
    release: {{ .Release.Name }}
  name: {{ template "odyssey.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ template "odyssey.fullname" . }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  template:
    metadata:
      labels:
        app: {{ template "odyssey.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.odyssey.image }}:{{ .Values.odyssey.imageTag }}"
        imagePullPolicy: {{ .Values.odyssey.imagePullPolicy | quote }}
        name: {{ template "odyssey.fullname" . }}
        resources:
          limits:
            cpu: 800m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /etc/odyssey/odyssey.conf
          name: odyssey
          subPath: odyssey.conf
      - args:
        - --web.listen-address=:9127
        - --web.telemetry-path=/metrics
        - --log.level=error
        - --log.format=logfmt
        - --pgBouncer.connectionString=postgres://127.0.0.1:6432/console?sslmode=disable&connect_timeout=10
        image: "{{ .Values.pgbouncer.image }}:{{ .Values.pgbouncer.imageTag }}"
        imagePullPolicy: {{ .Values.pgbouncer.imagePullPolicy | quote }}
        name: exporter
        ports:
        - containerPort: 9127
          name: exporter
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 150Mi
          requests:
            cpu: 30m
            memory: 40Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      initContainers:
      - command:
        - sh
        - -c
        - until pg_isready -h univ-postgres.postgres-prod.svc -p 5432 -U cheops_prod -d cheops; do echo
          waiting for database; sleep 2; done; sysctl -w net.core.somaxconn=2048 &&
          sysctl -w kernel.shm_rmid_forced=0 && sysctl -w kernel.msgmax=65536
        image: "{{ .Values.postgres.image }}:{{ .Values.postgres.imageTag }}"
        imagePullPolicy: {{ .Values.postgres.imagePullPolicy | quote }}
        name: wait-master
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: odyssey
        name: odyssey