---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "odyssey.fullname" . }}
    release: {{ .Release.Name }}
  name: {{ template "odyssey.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: default
    port: 6432
    protocol: TCP
    targetPort: 6432
  selector:
    app: {{ template "odyssey.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "odyssey.fullname" . }}
    release: {{ .Release.Name }}
  name: {{ template "odyssey.fullname" . }}-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: exporter
    port: 9127
    protocol: TCP
    targetPort: 9127
  selector:
    app: {{ template "odyssey.fullname" . }}
  sessionAffinity: None
  type: ClusterIP